[[main]]
  name = "Home"
  pageRef = "/"
  weight = 1

[[main]]
  name = "About"
  pageRef = "/about"
  weight = 10

[[main]]
  name = "Blogs"
  pageRef = "/blogs"
  weight = 20

[[main]]
  name = "Guestbook"
  pageRef = "/guestbook"
  weight = 30

[[footer]]
  name = "About"
  pageRef = "/about"
  weight = 10
