[[main]]
  name = "首页"
  pageRef = "/"
  weight = 1

[[main]]
  name = "关于"
  pageRef = "/about"
  weight = 10

[[main]]
  name = "博客"
  pageRef = "/blogs"
  weight = 20

[[main]]
  name = "留言板"
  pageRef = "/guestbook"
  weight = 30

[[footer]]
  name = "关于"
  pageRef = "/about"
  weight = 10
