baseURL = "https://bluhuang.github.io/blogs-of-bluhuang/"
title = "BluHuang's Blog"
theme = "hugoplate"
timeZone = "Asia/Shanghai"
summaryLength = 10
hasCJKLanguage = true
enableGitInfo = true
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[permalinks]
  page = "/:section/:slug/"

[pagination]
  disableAliases = false
  pagerSize = 30
  path = "page"

[build]
  [build.buildStats]
    enable = true

[[build.cachebusters]]
  source = "assets/notwatching/hugo_stats\\.json"
  target = "css"

[outputs]
  home = ["HTML", "RSS", "WebAppManifest", "SearchIndex"]
  page = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[imaging]
  quality = 80
  resampleFilter = "Lanczos"

[caches]
  [caches.images]
    dir = ":resourceDir/_gen"
    maxAge = "720h"
  [caches.assets]
    dir = ":resourceDir/_gen"
    maxAge = "720h"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = "monokai"
    lineNumbersInTable = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 5
    ordered = true

[mediaTypes]
  [mediaTypes."application/manifest+json"]
    suffixes = ["webmanifest"]

[outputFormats]
  [outputFormats.WebAppManifest]
    mediaType = "application/manifest+json"
    rel = "manifest"
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "searchindex"
    isPlainText = true
    notAlternative = true

# CSS Plugins
[[params.plugins.css]]
  link = "plugins/swiper/swiper-bundle.css"
  lazy = true
[[params.plugins.css]]
  link = "plugins/glightbox/glightbox.css"
  lazy = true
[[params.plugins.css]]
  link = "plugins/font-awesome/v6/brands.css"
  lazy = true
[[params.plugins.css]]
  link = "plugins/font-awesome/v6/solid.css"
  lazy = true
[[params.plugins.css]]
  link = "plugins/font-awesome/v6/icons.css"
  lazy = true

# KaTeX
[[params.plugins.css]]
  link = "https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css"
  attributes = 'integrity="sha384-nB0miv6/jRmo5UMMR1wu3Gz6NLsoTkbqJghGIsx//Rl+OelTgXHG+M0E5R2T7LG0" crossorigin="anonymous"'

# JS Plugins
[[params.plugins.js]]
  link = "js/search.js"
  lazy = false
[[params.plugins.js]]
  link = "plugins/swiper/swiper-bundle.js"
  lazy = false
[[params.plugins.js]]
  link = "plugins/glightbox/glightbox.js"
  lazy = true
[[params.plugins.js]]
  link = "js/gallery-slider.js"
  lazy = true
[[params.plugins.js]]
  link = "plugins/cookie.js"
  lazy = false
[[params.plugins.js]]
  link = "js/accordion.js"
  lazy = true
[[params.plugins.js]]
  link = "js/tab.js"
  lazy = true
[[params.plugins.js]]
  link = "js/modal.js"
  lazy = true
[[params.plugins.js]]
  link = "plugins/youtube-lite.js"
  lazy = true

[[params.plugins.js]]
  link = "https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js"
  lazy = false
[[params.plugins.js]]
  link = "https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js"
  lazy = true
